In [5]:
# import scipy and numpy 
from scipy import fft 
import numpy as np 
  
data = np.random.randn(5, 5) 
  
# use dct and dctn functions to calculate the discrete cosine transform
a = fft.dct(data)
b = fft.dctn(data)

print(a.shape)
print(b.shape)
print(data)
print(a)
print(b)
# print(gfg)

(5, 5)
(5, 5)
[[-0.71481135 -0.94966557  0.31043118 -0.08324053 -1.98671364]
 [ 0.56764968 -0.81982072 -0.76876548 -0.30964861 -0.19230251]
 [-1.64673451  0.63611832  0.55377829  0.7771361  -0.29472711]
 [ 0.05147647  0.44691844 -0.25051051 -1.12305466 -0.54752398]
 [ 0.68047694  0.81060616  0.09864745 -1.2711031  -0.79300522]]
[[-6.8479998   1.4007582  -4.35365054  3.14324917  0.62250528]
 [-3.04577529  0.84577169  2.84290587  1.86378238  0.52196611]
 [ 0.0511422  -2.73744723 -5.12234672 -1.32114827 -2.37902637]
 [-2.84538848  2.98498063  0.11627445 -2.28209905  0.28641615]
 [-0.94875555  5.24992564 -0.09476673 -2.22746415  0.8728483 ]]
[[-27.27355384  15.48797784 -13.22316731  -1.64735986  -0.15058107]
 [-11.45659819  -9.83634249  -4.89553092  15.08947974  -0.19927514]
 [ -9.07676011  13.86839183   1.21812909   4.38260175   6.67797794]
 [ -6.55381918  -0.45595052 -10.19297934  -1.57228294  -0.74233853]
 [  4.8157278   -7.56283326 -17.78202085  -1.39945969  -5.14186336]]


In [13]:
indexes = np.random.choice(10, 0, replace=False)
indexes

array([], dtype=int64)

In [7]:
indexes

array([9, 7, 2, 3, 0])

In [6]:
import torch
# 将真实标签转换为one-hot向量


# 将真实标签转换为one-hot向量

def smooth_labels(targets, smoothing=0.1):
    num_classes = 40
    # 将目标标签转换为one-hot表示形式
    targets_one_hot = torch.zeros(targets.size(0), num_classes, device=targets.device)
    targets_one_hot.scatter_(1, targets.view(-1, 1), 1)

    # 计算平滑后的标签分布
    targets_smoothed = (1.0 - smoothing) * targets_one_hot + smoothing / num_classes
    return targets_smoothed

# test smooth_labels
outputs = torch.tensor([[0.1, 0.9], [0.3, 0.7]])
targets = torch.tensor([1, 12])
smooth_labels(targets, smoothing=0.1)


tensor([[0.0025, 0.9025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025,
         0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025,
         0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025,
         0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025,
         0.0025, 0.0025, 0.0025, 0.0025],
        [0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025,
         0.0025, 0.0025, 0.0025, 0.9025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025,
         0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025,
         0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025,
         0.0025, 0.0025, 0.0025, 0.0025]])